// Generated by CoffeeScript 1.6.3
define(['underscore'], function(_) {
  var first, fofs, second, third;
  first = (function() {
    function first() {}

    first.prototype.v = 'in first';

    return first;

  })();
  second = (function() {
    second.prototype.m = 'in second';

    function second() {
      second.__super__.constructor.apply(this, arguments);
    }

    second.method = function(s) {
      return console.log(s);
    };

    return second;

  })();
  third = (function() {
    function third() {
      var s;
      s = new second();
    }

    return third;

  })();
  return fofs = (function() {
    function fofs() {}

    fofs.one = function(s) {
      return console.log;
    };

    return fofs;

  })();
});

/*
//@ sourceMappingURL=test.map
*/
